### ISSUE TITLE
Product table 변경 제안

### ISSUE THREAD

**Issue by Dev-Hi** [Kosmos-Project/catalog-service#2]
현재 Product table에따르면, category1, category2, category3이라는 attribute가 존재하는데요.
위처럼 사용하는 대신, 별도의 category table을 만드는 것이 좋다고 생각합니다.

왜냐하면 category는 사전에 정의되어야하기 때문입니다. 현재 category service에 대한 ERD에서는 category를 admin이 정의할 수 없고 오직 user에의해서만 등록됩니다. user마다 정의하는 category 체계가 다르기 때문에.. 결과적으로 user는 혼란스러울 것이라는 생각이 드네요.. 

혹시 의견있으시다면, comment 부탁드리겠습니다! @yijinKim  @NewCentury99

**Comment by NewCenturyDev** [comment]
좋은 방법일것 같습니다 차후 구현시 반영하면 좋을 것 같네요

**Comment by yijinKim** [comment]
네 저도 동의합니다. 해당 카테고리는 분리하는게 좋을듯합니다
