### ISSUE TITLE
catalog-service entity 검토 요청

### ISSUE THREAD

**Issue by yijinKim** [Kosmos-Project/catalog-service#3]
catalog-service에 필요한 entity들을 입력한 상태입니다. 
메인테이블은 product 테이블이고 category, attachment, position 테이블도 대략적으로 만들어놓은 상태입니다.
노션의 erd를 참고해서 엔티티 작성한 것이라서 혹시 수정해야할 부분이 있을지 리뷰 부탁드려요.

**Comment by NewCenturyDev** [comment]
확인해봤는데 ERD와도 꽤 부합하고 괜찮은 것 같습니다
차후에 Request DTO에는 Spring Validation을 하면 좋을 것 같은데, 어차피 지금은 Fetch(Read) 기능과 그에 따른 리스폰스만 구현하셨으니 해당사항이 없을 것으로 생각됩니다.

별다른 변수가 없다면 이대로 PR 여시고 머지하시면 될 것 같습니다 어프루브는 바로 눌러드릴게요

P.S. 변명이라면 변명이지만.. 제가 지금 월수금은 학교(+과제 + 팀플)를 다니고 화목토는 프리랜서 겸 알바 겸 인턴 비스무리한 걸로 회사를 다니면서 앱+백엔드개발을 하고 있는데욥.. (일요일은 본가에 왔다갔다하면서 자취에 필요한것들을 채워넣고 있습니다)
그렇게 주 6일이 꽉차고 하필이면 팀플이랑 어려운 과제에 이번주 목요일 회사 출장(광주광역시)까지 겹치면서 정신이 없게되어 답장이 꽤 늦게 된 점 대단히 죄송합니다. 약간의.. 양해를 부탁드립니다.. ㅠㅠ
